// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2JZUkRvMtgt1FB8mM9d6UioDQxMN_wBU',
    appId: '1:17452579985:web:6a6dd111f88d9e85235330',
    messagingSenderId: '17452579985',
    projectId: 'booking-barbershop-a9dc4',
    authDomain: 'booking-barbershop-a9dc4.firebaseapp.com',
    storageBucket: 'booking-barbershop-a9dc4.firebasestorage.app',
    measurementId: 'G-0QKZ0DC7J7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO0Wuu5IIWjVG4F5HSwkY-n6vrQoTGlg0',
    appId: '1:17452579985:android:ae107f58393c16cf235330',
    messagingSenderId: '17452579985',
    projectId: 'booking-barbershop-a9dc4',
    storageBucket: 'booking-barbershop-a9dc4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtVXNRO8Vxu0Y6vj4JtpxCpue_4IRM95g',
    appId: '1:17452579985:ios:224728d96116cc17235330',
    messagingSenderId: '17452579985',
    projectId: 'booking-barbershop-a9dc4',
    storageBucket: 'booking-barbershop-a9dc4.firebasestorage.app',
    iosClientId: '17452579985-mdgn96u4n8t6ta2vb2tsiahdin7a3cgi.apps.googleusercontent.com',
    iosBundleId: 'com.m4gung.barbershop.adminMobileApp',
  );
}
